
# the site
site_name: The Next Generation Logic Framework
site_url: https://www.logicng.org
site_description: LogicNG
site_author: BooleWorks GmbH

# the repository
repo_name: logic-ng/LogicNG
repo_url: https://github.com/logic-ng/LogicNG
edit_uri: ""

# Copyright
copyright: Copyright &copy; BooleWorks GmbH

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
        primary: teal
        accent: teal
plugins:
  - search
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/booleworks/
      name: BooleWorks on GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/booleworks
      name: Booleorks on LinkedIn

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
     custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: logic-ng
      repo: LogicNG
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.tilde
  - tables
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Tutorial:
    - tutorial/index.md
    - Chapter 1 Problem Modelling: tutorial/chapter1.md
    - Chapter 2 Formulas: tutorial/chapter2.md
    - Chapter 3 Formula Functions: tutorial/chapter3.md
    - Chapter 4 Propositions: tutorial/chapter4.md
    - Chapter 5 SAT Solving: tutorial/chapter5.md
    - Chapter 6 MaxSAT Solving: tutorial/chapter6.md
  - Documentation:
    - documentation/index.md
    - The Formula Factory: documentation/formula-factory.md
    - Formulas:
      - documentation/formulas/index.md
      - Cardinality Constraints: documentation/formulas/cardinality-constraints.md
      - Pseudo-Boolean Constraints: documentation/formulas/pb-constraints.md
    - Formula Operations:
      - documentation/formulas/operations/index.md
      - Formula Functions: documentation/formulas/operations/formula-functions.md
      - Formula Predicates: documentation/formulas/operations/formula-predicates.md
      - Formula Transformations:
        - documentation/formulas/operations/transformations/index.md
        - Normal Form Transformations: documentation/formulas/operations/transformations/normal-form-transformations.md
        - Simplifier Transformations: documentation/formulas/operations/transformations/simplifier-transformations.md
        - Other Transformations: documentation/formulas/operations/transformations/other-transformations.md
    - Propositions: documentation/propositions.md
    - Solvers:
      - documentation/solvers/index.md
      - SAT Solving: documentation/solvers/sat-solving.md
      - MaxSAT Solving: documentation/solvers/maxsat-solving.md
    - Knowledge Compilation:
      - documentation/knowledge-compilation/index.md
      - BDD: documentation/knowledge-compilation/bdd.md
      - DNNF: documentation/knowledge-compilation/dnnf.md
    - Backbones: documentation/backbones.md
    - Model Counting and Enumeration: documentation/model-counting-enumeration.md
    - Explanations:
      - documentation/explanations/index.md
      - Unsat Cores: documentation/explanations/unsat-cores.md
      - MUS: documentation/explanations/mus.md
      - Smallest MUS: documentation/explanations/smus.md
    - Handlers: documentation/handlers.md
    - Graphs: documentation/graphs.md
    - I/O: documentation/io.md
  - Legal:
    - Privacy Policy: legal/privacy.md
    - Corporate Information: legal/corporate.md
